# Generated by Django 5.0.1 on 2024-03-19 12:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artist_date_alter_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(default='artist.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
