# Generated by Django 5.0.1 on 2024-03-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_mfd_product_stock_count_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='authenic_rating',
            new_name='authentic_rating',
        ),
    ]
