# Generated by Django 5.0.1 on 2024-03-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_authenic_rating_artist_authentic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='shipping_on_time',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
